global:
   scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
       - targets: ['<YOUR_IP>:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['<YOUR_IP>:9100', 'IP_ADDR#2:9100', 'IP_ADDR#3:9100']

  - job_name: 'node_exporter_server_confluent'
    static_configs:
    - targets: ['<YOUR_IP>:9100']

  - job_name: 'jmx_exporter_zookeeper'
    static_configs:
    - targets: ['<YOUR_IP>:8181']

  - job_name: 'jmx_exporter_kafka'
    static_configs:
    - targets: ['<YOUR_IP>:8282']



