{
 "title": "BRAINWORX RND",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "[NODE_2] DISK FREE SPACE LINUX CONFLUENT SERVER",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/ploop26458p1\",fstype=\"ext4\",instance=\"5.181.217.200:9100\",job=\"node_exporter_server_confluent\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "[NODE_2] NETWORK LINUX CONFLUENT SERVER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"5.181.217.200:9100\", job=\"node_exporter_server_confluent\"}[1m])"
    }
   ]
  },
  {
   "title": "[NODE_2] CPU USAGE - LINUX CONFLUENT SERVER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"node_exporter_server_confluent\",mode=\"system\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "[JMX_2] CONFLUENT KAFKA ONLY CPU USAGE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"jmx_exporter_kafka\",instance=\"5.181.217.200:8282\"}[1m])) / sum(count(node_cpu_seconds_total{job=\"node_exporter_server_confluent\",mode=\"system\"})) * 100"
    }
   ]
  },
  {
   "title": "[NODE_2] CPU (4 CORE) USAGE LINUX CONFLUENT SERVER [ MAINTENANCE ]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(irate(node_cpu_seconds_total{job=\"node_exporter_server_confluent\",mode=\"system\"}[1m]) * 10 ) /4"
    }
   ]
  },
  {
   "title": "[JMX_2] CONFLUENT KAFKA MEMORY USED",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"jmx_exporter_kafka\",instance=\"5.181.217.200:8282\"}"
    }
   ]
  },
  {
   "title": "[JMX_2] NETWORK METADATA KAFKA TOTAL REQUEST",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requests_total{instance=\"5.181.217.200:8282\",job=\"jmx_exporter_kafka\",request=\"Metadata\",version=\"9\"}"
    }
   ]
  },
  {
   "title": "[JMX_2] KAFKA PARTITIONS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globalpartitioncount{instance=\"5.181.217.200:8282\",job=\"jmx_exporter_kafka\"}"
    }
   ]
  },
  {
   "title": "[JMX_2] NETWORK KAFKA PRODUCER TOTAL REQUEST",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requests_total{instance=\"5.181.217.200:8282\",job=\"jmx_exporter_kafka\",request=\"Produce\",version=\"8\"}"
    }
   ]
  },
  {
   "title": "[JMX_1] ZOOKEEPER DATA SIZE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "zookeeper_DataDirSize{instance=\"5.181.217.200:8181\",job=\"jmx_exporter_zookeeper\"}"
    }
   ]
  },
  {
   "title": "[JMX_2] NETWORK KAFKA CONSUMER TOTAL REQUEST",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requests_total{instance=\"5.181.217.200:8282\",job=\"jmx_exporter_kafka\",request=\"FetchConsumer\",version=\"11\"}"
    }
   ]
  },
  {
   "title": "[JMX_1] ZOOKEEPER ALIVE CONNECTION",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(zookeeper_NumAliveConnections{instance=\"5.181.217.200:8181\",job=\"jmx_exporter_zookeeper\"})"
    }
   ]
  },
  {
   "title": "[NODE_2] NETWORK ICMP ERROR  - LINUX CONFLUENT SERVER",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_netstat_Icmp_InErrors{instance=\"5.181.217.200:9100\",job=\"node_exporter_server_confluent\"}"
    }
   ]
  },
  {
   "title": "[JMX_1] ZOOKEEPER PACKETS RECEIVED",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "zookeeper_PacketsReceived{instance=\"5.181.217.200:8181\",job=\"jmx_exporter_zookeeper\"}"
    }
   ]
  },
  {
   "title": "[NODE_2] NETWORK ICMP OUT - LINUX CONFLUENT SERVER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Icmp_OutMsgs{instance=\"5.181.217.200:9100\",job=\"node_exporter_server_confluent\"}"
    }
   ]
  },
  {
   "title": "[JMX_1] ZOOKEEPER PACKETS SENT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "zookeeper_PacketsSent{instance=\"5.181.217.200:8181\",job=\"jmx_exporter_zookeeper\"}"
    }
   ]
  },
  {
   "title": "[NODE_2] NETWORK ICMP IN - LINUX CONFLUENT  SERVER",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Icmp_InMsgs{instance=\"5.181.217.200:9100\",job=\"node_exporter_server_confluent\"}"
    }
   ]
  },
  {
   "title": "[JMX_2] KAFKA TOPIC USER (MESSAGE IN)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{instance=\"5.181.217.200:8282\",job=\"jmx_exporter_kafka\",topic=\"users\"}"
    }
   ]
  },
  {
   "title": "[NODE_2] FREE SWAP - LINUX CONFLUENT SERVER",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes{instance=\"5.181.217.200:9100\",job=\"node_exporter_server_confluent\"}"
    }
   ]
  },
  {
   "title": "[JMX_2] KAFKA TOPIC PAGEVIEWS (MESSAGE IN)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{instance=\"5.181.217.200:8282\",job=\"jmx_exporter_kafka\",topic=\"pageviews\"}\r"
    }
   ]
  },
  {
   "title": "[NODE_2] FREE RAM - LINUX CONFLUENT SERVER",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"5.181.217.200:9100\",job=\"node_exporter_server_confluent\"}"
    }
   ]
  },
  {
   "title": "[JMX_2] PRODUCER KAFKA THROTTLE TIME ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_throttletimems_count{instance=\"5.181.217.200:8282\",job=\"jmx_exporter_kafka\",request=\"Produce\"}"
    }
   ]
  },
  {
   "title": "[JMX_2] KAFKA DISK WRITE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_linux_disk_write_bytes{instance=\"5.181.217.200:8282\",job=\"jmx_exporter_kafka\"}"
    }
   ]
  },
  {
   "title": "[JMX_2] CONSUMER KAFKA THROTTLE TIME ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_throttletimems_count{instance=\"5.181.217.200:8282\",job=\"jmx_exporter_kafka\",request=\"FetchConsumer\"}"
    }
   ]
  },
  {
   "title": "[JMX_2] KAFKA DISK READ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_linux_disk_read_bytes{instance=\"5.181.217.200:8282\",job=\"jmx_exporter_kafka\"}"
    }
   ]
  }
 ]
}